export default [
  {
    id: '1',
    menuName: 'home',
    invokeUrl: '/index',
    iconStr: 'iconhome-fill',
    subMenus: [],
  },
  {
    id: '2',
    menuName: 'documentation',
    invokeUrl: '/documentation',
    iconStr: 'iconfavorites-fill',
    subMenus: [],
  },
  {
    id: '3',
    menuName: 'guide',
    invokeUrl: '/guide',
    iconStr: 'icongold-supplie-fill',
    subMenus: [],
  },
  {
    id: '4',
    menuName: 'table.default',
    invokeUrl: '/table',
    iconStr: 'iconcoupons-fill',
    subMenus: [
      {
        id: '5',
        menuName: 'table.dynamic',
        invokeUrl: '/table/dynamic/index',
        iconStr: 'iconCurrencyConverter-fill',
        subMenus: [],
      },
    ],
  },
  {
    id: '6',
    menuName: 'condition',
    invokeUrl: '/condition',
    iconStr: 'iconimage-text-fill',
    subMenus: [],
  },
  {
    id: '14',
    menuName: 'system.option.dataelement',
    invokeUrl: `/iframe/${process.env.VUE_APP_IFRAME}`,
    subMenus: [],
  },
  {
    id: '998',
    menuName: 'test',
    invokeUrl: '/test',
    iconStr: 'iconsmile-fill',
    subMenus: [],
  },
  {
    id: '999',
    menuName: 'icon',
    invokeUrl: '/icon',
    iconStr: 'iconcollection-fill',
    subMenus: [],
  },
];
