export default [
  {
    id: '1',
    menuName: 'home',
    invokeUrl: '/index',
    iconStr: 'iconhome-fill',
    subMenus: [],
  },
  {
    id: '2',
    menuName: 'documentation',
    invokeUrl: '/documentation',
    iconStr: 'iconfavorites-fill',
    subMenus: [],
  },
  {
    id: '3',
    menuName: 'guide',
    invokeUrl: '/guide',
    iconStr: 'icongold-supplie-fill',
    subMenus: [],
  },
  {
    id: '4',
    menuName: 'table.default',
    invokeUrl: '/table',
    iconStr: 'iconcoupons-fill',
    subMenus: [
      {
        id: '5',
        menuName: 'table.dynamic',
        invokeUrl: '/table/dynamic',
        subMenus: [],
      },
      {
        id: '14',
        menuName: 'table.drag',
        invokeUrl: '/table/drag',
        subMenus: [],
      },
    ],
  },
  {
    id: '10',
    menuName: 'form.default',
    invokeUrl: '/form',
    iconStr: 'iconall-fill',
    subMenus: [
      {
        id: '11',
        menuName: 'form.layout',
        invokeUrl: '/form/layout',
        subMenus: [],
      },
      {
        id: '12',
        menuName: 'form.basic',
        invokeUrl: '/form/basic',
        subMenus: [],
      },
      {
        id: '13',
        menuName: 'form.communication',
        invokeUrl: '/form/communication',
        subMenus: [],
      },
    ],
  },
  {
    id: '6',
    menuName: 'condition',
    invokeUrl: '/condition',
    iconStr: 'iconimage-text-fill',
    subMenus: [],
  },
  {
    id: '14',
    menuName: 'comprehensive',
    invokeUrl: '/comprehensive',
    iconStr: 'icontopraning-fill',
    subMenus: [],
  },
  {
    id: '15',
    menuName: 'error.default',
    invokeUrl: '/error',
    iconStr: 'iconstop-fill',
    subMenus: [
      {
        id: '16',
        menuName: 'error.one',
        invokeUrl: '/404',
        subMenus: [],
      },
      {
        id: '17',
        menuName: 'error.two',
        invokeUrl: '/401',
        subMenus: [],
      },
    ],
  },
  {
    id: '7',
    menuName: 'iframe',
    invokeUrl: `/iframe/${process.env.VUE_APP_IFRAME}`,
    iconStr: 'iconproduct1',
    subMenus: [],
  },
  {
    id: '20',
    menuName: 'excel.default',
    invokeUrl: '/excel',
    iconStr: 'iconfeeds-fill',
    subMenus: [
      {
        id: '21',
        menuName: 'excel.export',
        invokeUrl: '/excel/export',
        subMenus: [],
      },
    ],
  },
  {
    id: '8',
    menuName: 'test',
    invokeUrl: '/test',
    iconStr: 'iconsmile-fill',
    subMenus: [],
  },
  {
    id: '9',
    menuName: 'icon',
    invokeUrl: '/icon',
    iconStr: 'iconcollection-fill',
    subMenus: [],
  },
  {
    id: '22',
    menuName: 'components.default',
    invokeUrl: '/components',
    iconStr: 'iconfolder-fill',
    subMenus: [
      {
        id: '23',
        menuName: 'components.quill',
        invokeUrl: '/components/quill',
        subMenus: [],
      },
      {
        id: '24',
        menuName: 'components.dialog',
        invokeUrl: '/components/dialog',
        subMenus: [],
      },
      {
        id: '25',
        menuName: 'components.cropper',
        invokeUrl: '/components/cropper',
        subMenus: [],
      },
    ],
  },
  {
    id: '26',
    menuName: 'pdf',
    invokeUrl: '/pdf',
    iconStr: 'iconpin-fill',
    subMenus: [],
  },
];
