export default [
  {
    id: '1',
    menuName: 'home',
    invokeUrl: '/index',
    iconStr: 'iconhome-fill',
    subMenus: [],
  },
  {
    id: '2',
    menuName: 'documentation',
    invokeUrl: '/documentation',
    iconStr: 'iconfavorites-fill',
    subMenus: [],
  },
  {
    id: '3',
    menuName: 'guide',
    invokeUrl: '/guide',
    iconStr: 'icongold-supplie-fill',
    subMenus: [],
  },
  {
    id: '4',
    menuName: 'table.default',
    invokeUrl: '/table',
    iconStr: 'iconcoupons-fill',
    subMenus: [
      {
        id: '5',
        menuName: 'table.dynamic',
        invokeUrl: '/table/dynamic/index',
        subMenus: [],
      },
    ],
  },
  {
    id: '10',
    menuName: 'form.default',
    invokeUrl: '/form',
    iconStr: 'iconcoupons-fill',
    subMenus: [
      {
        id: '11',
        menuName: 'form.layout',
        invokeUrl: '/form/layout',
        subMenus: [],
      },
      {
        id: '12',
        menuName: 'form.basic',
        invokeUrl: '/form/basic',
        subMenus: [],
      },
    ],
  },
  {
    id: '6',
    menuName: 'condition',
    invokeUrl: '/condition',
    iconStr: 'iconimage-text-fill',
    subMenus: [],
  },
  {
    id: '7',
    menuName: 'iframe',
    invokeUrl: `/iframe/${process.env.VUE_APP_IFRAME}`,
    iconStr: 'iconproduct1',
    subMenus: [],
  },
  {
    id: '8',
    menuName: 'test',
    invokeUrl: '/test',
    iconStr: 'iconsmile-fill',
    subMenus: [],
  },
  {
    id: '9',
    menuName: 'icon',
    invokeUrl: '/icon',
    iconStr: 'iconcollection-fill',
    subMenus: [],
  },
];
